### ISSUE TITLE
Wider bencmarks

### ISSUE THREAD

**Issue by willbasky** [fumieval/oath#1]
I extended a number of benchmarks to more threads and got new stats:
```
...
  oath 10000:      OK (0.15s)
    47.1 ms ± 4.3 ms
  async 10000:     OK (1.37s)
    43.1 ms ± 607 μs
  streamly 10000:  OK (1.75s)
    237  ms ±  17 ms
  oath 100000:     OK (34.22s)
    5.000 s ± 185 ms
  async 100000:    OK (3.52s)
    477  ms ±  23 ms
  streamly 100000: OK (17.51s)
    2.345 s ± 183 ms
```
Why it is so?

**Comment by fumieval** [comment]
Are you referring to 5.000s? In general when there are too many `readTVar`s at the same time, the performance degrades

**Comment by willbasky** [comment]
Yeah, to 5s. Got it. So, did `oath` lose the race to `async` with too many threads?

**Comment by fumieval** [comment]
Yes
